"""add used_id to journal model

Revision ID: aa871804de24
Revises: 
Create Date: 2024-10-05 21:06:23.186049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa871804de24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('future',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('future',
               existing_type=sa.String(length=5000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.String(length=5000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
